### ISSUE TITLE
Deploy workflow for Github Pages doesn't work

### ISSUE THREAD

**Issue by kchristidis** [apas/athena#1]
Not sure if I'm deviating from the workflow somehow, or whether this is indeed an error with the build script, but the 10-step workflow fails at Step 8.

![screen shot 2016-06-12 at 13 55 27](https://cloud.githubusercontent.com/assets/14876848/15992887/75d72066-30a5-11e6-81d7-a21ff2a80d7a.png)

(First command in the screenshot above just goes to show that the `*.github.io` directory is not a repo, despite what the path suggests.)

It looks like the `python athena.py build` overwrites the contents of the `.git` folder in the `build` dir.

Here's what the `.git` folder looks like after Step 4):

```
total 24
drwxr-xr-x  10 kchrist  staff  340 Jun 12 14:00 .
drwxr-xr-x   7 kchrist  staff  238 Jun 12 14:00 ..
-rw-r--r--   1 kchrist  staff   23 Jun 12 14:00 HEAD
drwxr-xr-x   2 kchrist  staff   68 Jun 12 14:00 branches
-rw-r--r--   1 kchrist  staff  260 Jun 12 14:00 config
-rw-r--r--   1 kchrist  staff   73 Jun 12 14:00 description
drwxr-xr-x  11 kchrist  staff  374 Jun 12 14:00 hooks
drwxr-xr-x   3 kchrist  staff  102 Jun 12 14:00 info
drwxr-xr-x   4 kchrist  staff  136 Jun 12 14:00 objects
drwxr-xr-x   4 kchrist  staff  136 Jun 12 14:00 refs
```

And here's what you get after Step 7:

```
total 0
drwxr-xr-x  5 kchrist  staff  170 Jun 12 14:01 .
drwxr-xr-x  7 kchrist  staff  238 Jun 12 14:00 ..
drwxr-xr-x  2 kchrist  staff   68 Jun 12 14:00 branches
drwxr-xr-x  4 kchrist  staff  136 Jun 12 14:00 objects
drwxr-xr-x  4 kchrist  staff  136 Jun 12 14:00 refs
```

**Comment by apas** [comment]
Pretty sure I fixed it. `pull` the latest commit (a46232a) from master; i) optionally create a build directory manually beforehand, `git init` afterwards, and `athena build`, or ii) have athena build the directory automatically, `git init`, and then rebuild with a new test post. Let me know if you still encounter any problems.

**Comment by kchristidis** [comment]
Works now, thank you.
