### ISSUE TITLE
Using HTML in footer?

### ISSUE THREAD

**Issue by lordgrenville** [apas/athena#12]
Once again, thanks for making this, I really like it! 

I'd like to put a link in the footer (actually to this repository), but editing the footer in the `config.py` just seems to be translated into plain text, so I can't use Markdown or HTML. Any way around this?

**Comment by apas** [comment]
Good catch, I've not thought about it. I'll explore possible solutions.

**Comment by apas** [comment]
In the meantime, you can edit the footer in the HTML templates.

**Comment by lordgrenville** [comment]
Ah yeah, that works. It has to be done on each post, but I'm sure I can concoct some kind of recursive perl find-replace.

**Comment by apas** [comment]
No, it has to be done once in each .html file in the templates directory. Posts are generated automatically.

**Comment by lordgrenville** [comment]
Should have clarified - I'm hosting on Github, and my repository is in the `build` folder. So I navigate to there and recursively `s/old footer/<a href="link">new</a> footer/` for all *.html files.

**Comment by apas** [comment]
Before you build you can simply change the footer in the html files in the templates directory. Where you host is irrelevant.

**Comment by lordgrenville** [comment]
Oh, I see - done, thanks.

What's the difference between `hard.html` and `page.html`?

**Comment by lordgrenville** [comment]
Ah, now I see. Thanks!
