### ISSUE TITLE
Install issue with pandoc-sidenote

### ISSUE THREAD

**Issue by theconsultant** [apas/athena#4]
Hi Apas! Saw your project on HN and decided to give it a try.. brew installing pandoc-sidenote fails, and i'm not in the headspace to learn to compile Haskell to get it running (from https://github.com/jez/pandoc-sidenote) :-)

I'm going to try Athena without it and see what happens..

**Comment by jdbrewer** [comment]
You can run: `brew install jez/formulae/pandoc-sidenote`

**Comment by theconsultant** [comment]
.. and now I see that on jez's site. Right, thanks. Time to take a break from the computer ;-)

**Comment by apas** [comment]
@theconsultant, @jdbrewer is correct. I mistakenly entered the wrong command in the readme; will fix now. Time for _me_ to take a break from the computer.
